FROM fedora:36
#redhat universal base image 8

# Env & Arg variables
ARG USERNAME=ansible
ARG USERPASS=ansible
EXPOSE 22

RUN yum update -y 
RUN yum install -y \
  systemd systemd-sysv dbus \
  openssh-server sudo acl vim \
  python3 python3-pip nmap-ncat rsync \
  createrepo coreutils curl mailx git \
  wget procps


# Add a non-root user & set password
RUN useradd -ms /bin/bash $USERNAME


# Create the ssh directory and authorized_keys file
USER $USERNAME
RUN mkdir /home/$USERNAME/.ssh
COPY ansiblekey.pub /home/$USERNAME/.ssh/authorized_keys

USER root
RUN chown $USERNAME /home/$USERNAME/.ssh/authorized_keys && \
    chmod 600 /home/$USERNAME/.ssh/authorized_keys
RUN echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL " >> /etc/sudoers

COPY docker-entrypoint_rhel.sh /docker-entrypoint_rhel.sh
RUN chmod +x /docker-entrypoint_rhel.sh
ENTRYPOINT ["/docker-entrypoint_rhel.sh"]
