FROM ubuntu:latest

# Env & Arg variables
ARG USERNAME=ansible
ARG USERPASS=ansible
EXPOSE 22

RUN apt update -y 
RUN apt install -y systemd systemd-sysv dbus dbus-user-session openssh-server whois sudo acl vim python3 python3-pip netcat-openbsd iputils-ping rsync procps tar 


# Add a non-root user & set password
RUN useradd -ms /bin/bash $USERNAME

# Create the ssh directory and authorized_keys file
USER $USERNAME
RUN mkdir /home/$USERNAME/.ssh
COPY ./ssh_keys/splunk_docker_key.id.pub /home/$USERNAME/.ssh/authorized_keys

USER root
RUN chown $USERNAME /home/$USERNAME/.ssh/authorized_keys && \
    chmod 600 /home/$USERNAME/.ssh/authorized_keys
RUN echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL " >> /etc/sudoers

COPY ./entrypoint/docker-entrypoint_ubuntu.sh /docker-entrypoint_ubuntu.sh
RUN chmod +x /docker-entrypoint_ubuntu.sh
ENTRYPOINT ["/docker-entrypoint_ubuntu.sh"]
