---
- name: "REBOOT | Tasks depends on distribution"
  debug:
    var: ansible_distribution

# When the target runs under CENTOS / REDHAT
- name: "PATCH | Include tasks for CentOS & RedHat tasks"
  include_tasks: "linux_tasks/reboot_redhat_centos.yml"
  when: ansible_distribution in rhel_distribs

# When the target runs under Debian / Ubuntu
- name: "PATCH | Inlude tasks for Debian & Ubuntu tasks"
  include_tasks: "linux_tasks/reboot_debian_ubuntu.yml"
  when: ansible_distribution in debian_distribs

# # Reboot the target after the update
# - name: "REBOOT | Reboot triggered"
#   reboot:
#     msg: "Reboot initiated by Ansible. Related to Patch Management."
#     reboot_timeout: 600
#     test_command: "whoami"
#     post_reboot_delay: 15
#   changed_when: false
#   become: true
#   become_user: "root"
#   tags: molecule-notest

# - name: "REBOOT | Ensure we are not in rescue mode"
#   wait_for_connection:
#     timeout: 120