---
- name: add root user to docker group
  block:
  - name: add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    become: true
    register: add_root_to_docker_group_result

  - name: Reset ssh connection to allow user changes to affect ansible user
    ansible.builtin.meta: reset_connection
    # when: add_root_to_docker_group_result.changed

- name: add current user to docker group
  block:
  - name: add user to docker group
    user:
      name: "{{ ansible_user_id }}"
      groups: docker
      append: yes
    become: false
    register: add_user_to_docker_group_result

  - name: Reset ssh connection to allow user changes to affect ansible user
    ansible.builtin.meta: reset_connection
    # when: add_user_to_docker_group_result.changed

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection
