---
- name: generate SSH key "{{ssh_key_filename}}"
  openssh_keypair:
    path: "~/.ssh/{{ ssh_key_filename }}"
    #passphrase: "{{ ssh_key_password }}"
    type: rsa
    size: 4096
    state: present
    force: no

- name: copy SSH-key locally, to ansible-role. keys are used to gain access to docker containers
  copy:
    src: "~/.ssh/{{ item }}"
    dest: "{{ dockerfile_custom_images_path }}/ssh_keys/{{ item }}"
  with_items:
    - "{{ ssh_key_filename }}"
    - "{{ ssh_key_filename }}.pub"
  delegate_to: localhost

- name: Evaluating the authentication agent & adding the key...
  shell: |
    eval "$(ssh-agent)"
    ssh-add ~/.ssh/{{ ssh_key_filename }}