---
### Update known_hosts verification or else complains about MITM attack as host keys have changed 
- name: "refresh ~/.ssh/known_hosts file for key verification: get hostnames"
  shell: docker inspect -f '{{ '{{' }}.Config.Hostname{{ '}}' }}' $(docker container ls -af label=docker_compose_file={{ docker_compose_file_name }} -aq)
  become: true
  register: hostnames
  changed_when: false
  ignore_errors: true

- name: "Bugfix: workaround of ansible moduel:known_hosts doesn't update. "
  lineinfile:
    path: ~/.ssh/known_hosts
    state: absent
    regexp: "^{{ item }}"
  changed_when: false
  with_items:
    - "{{ hostnames.stdout_lines }}"

- name: "refresh ~/.ssh/known_hosts file for key verification: keyscan"
  known_hosts:
    state: present
    name: "{{ item }}"
    key: "{{ lookup('pipe', 'ssh-keyscan {{ item }}') }}"
  become: false
  changed_when: false
  with_items:
    - "{{ hostnames.stdout_lines }}"