---
# - name: override container image
#   set_fact: docker_image_custom_name=splk_ubuntu_latest_with_predistributed_splunk

- name: Fill in variables in Docker-Compose file
  template: 
    src: "{{ docker_compose_files_path }}/{{ docker_compose_file_name }}.compose.j2"
    dest: "{{ docker_compose_files_path }}/{{ docker_compose_file_name }}"
# State: compose file is ready to be used

- name: "Docker-Compose up: spin up containers from compose file"
  docker_compose:
    project_src: "{{ docker_compose_files_path }}"
    files: "{{ docker_compose_file_name }}"
    build: yes
    state: present
  register: output
# State: containers are Up and running