# yaml-language-server: $schema=../../docker_vars_schema.json

server_names_list:
  - name: uf1.lab
    instancetype: 
      - uf
  - name: uf2.lab
    instancetype: 
      - uf
  - name: ds.lab
    instancetype: 
      - deploymentserver
      - licensemaster
      - full
  - name: cm.lab
    instancetype: 
      - clustermanager
      - full
  - name: sh1.lab
    instancetype: 
      - search
      - full
  - name: idx1.lab
    instancetype: 
      - indexer
      - full
  - name: idx2.lab
    instancetype: 
      - indexer
      - full
  - name: idx3.lab
    instancetype: 
      - indexer
      - full


environment_dir: "development"
#dockerfile_baseimage: "ubuntu:latest" # E.g. fedora:36 OR ubuntu:latest. Find baseimages on hub.docker.com
dockerfile_baseimage: "ubuntu:latest" 
simulated_vm_os_family:  "{% if ('ubuntu' in dockerfile_baseimage or 'debian' in dockerfile_baseimage) %}Debian{% elif ('centos' in dockerfile_baseimage or 'rocky' in dockerfile_baseimage) %}Centos{% else %}RedHat{% endif %}"  # Either "Debian" OR "RedHat" uses role/vars/Debian.yml variables. Need to match dockerfile_baseimage

#following compose file will be generated based on {{ server_names_list }} above
docker_compose_file_name: "{{ docker_vars_file }}" 
docker_image_custom_name: "splunk_image_{{ dockerfile_baseimage | replace(':', '_') }}"


