---
docker_image_custom_name: "splunk_image_{{ dockerfile_baseimage | replace(':', '_') }}" # 
docker_compose_file_name: "{{ docker_vars_file }}" # use the same name as the docker_vars_file by default. E.g. the docker vars file is named deploymentlab.yml, then this variable will be named deploymentlab

# Automatically determine desired splunk version string
splunk_file: "{{ splunk_package_url | regex_search('(splunk(?:forwarder)?\\-\\d+[^/]*\\.tgz)') }}"
splunk_v: "{{ splunk_package_url | regex_search('(\\d+\\.\\d+\\.\\d+(?:\\.\\d+)?)') }}"
splunk_build: "{{ splunk_package_url | regex_search('\\d+\\.\\d+\\.\\d+(?:\\.\\d+)?\\-([^-]+)','\\1') | first }}"
# Create desired splunk version string (to compare with the output from the splunk version command for upgrades)
splunk_version: "{{ splunk_product }} {{ splunk_v }} (build {{ splunk_build }})"
splunk_auth: "{{ splunk_admin_username }}:{{ splunk_admin_password }}"

#docker_compose variables
docker_compose_files_path: "{{ role_path }}/files/docker_compose_files"
docker_compose_file: "{{ docker_compose_files_path }}/{{ docker_compose_file_name }}.compose"

ansible_inventory_path: "../environments/{{ environment_dir }}"
ansible_inventory_filename: "inventory_{{ docker_compose_file_name }}.ini"
ansible_inventory_file: "{{ ansible_inventory_path }}//{{ ansible_inventory_filename }}"



#########################
#### dockerfile variables
#########################
#extract image name from {{ dockerfile_baseimage }}
docker_entrypoint_path: "{{ role_path }}/files/docker_image/custom_dockerfile/entrypoint"
dockerfile_custom_images_path: "{{ role_path }}/files/docker_image/custom_dockerfile"
ssh_keys_path: "{{ dockerfile_custom_images_path }}/ssh_keys"

dockerfile_baseimage_image_name: "{{ dockerfile_baseimage | regex_search('(^[^:]+)', '\\1') | first  }}"
dockerfile_baseimage_tag_name: "{{ dockerfile_baseimage | regex_search('^[^:]+:([^:]+)', '\\1')  | first }}"
dockerfile_custom_filename: "Dockerfile_{{ dockerfile_baseimage_image_name }}_{{ dockerfile_baseimage_tag_name }}"

#docker_image_path: "{{ role_path }}/files/docker_image"
#docker_image_custom_name: "splk_{{ dockerfile_baseimage_image_name }}_{{ dockerfile_baseimage_tag_name }}" #documented out because overrides when creating image based on digest


docker_entrypoint: "{{ docker_entrypoint_path }}/{{ docker_entrypoint_filename }}"


